services:
  - type: web
    name: busconnect-api
    env: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/BusConnectAPI.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
